#!/usr/bin/env php
<?php

require_once __DIR__.'/NavigatorKernel.php';

use Symfony\Framework\WebBundle\Console\Application;

$kernel = new NavigatorKernel('dev', true);

$application = new Application($kernel);
$application->run();
